project:
  type: website
  output-dir: docs

website:
  title: "UO Simulation Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: simulations/sim1/index.qmd
        text: Simulation 1
      - href: simulations/sim2/index.qmd
        text: Simulation 2
      - href: resources/index.qmd
        text: Resources
      - href: instructor/index.qmd
        text: Instructor

format:
  html:
    theme: cosmo
    toc: false
    page-layout: full
    css: styles.css